blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", views.blog_index, name = 'blog_index'),
    path("post/<int:pk>/", views.post_detail, name = 'post_detail')
] 

urlpatterns += staticfiles_urlpatterns()
app_name = "blog"

core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views



urlpatterns = [
    path("", views.index, name = "index"),
    path("resume/", views.resume, name = "resume")
]
app_name = "core"

jordantwells/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', 'core'), name = 'core'),
    path('blog/', include('blog.urls', 'blog'), name = 'blog'),
    path('webapps/', include('webapps.urls', 'webapps'), name = 'webapps'),
]

webapps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path("", views.webapps, name = 'webapps-index'),
    path("lyric-cloud/", views.lyric_cloud, name = "lyric_cloud"),
   # path("lyric-cloud/authenticate/", views.lyric_cloud_auth, name = "lyric_cloud_auth")
] 
urlpatterns += staticfiles_urlpatterns()
app_name = "webapps"

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=20)

	def __str__(self):
		return self.name

class Post(models.Model):
	title = models.CharField(max_length = 255)
	description = models.CharField(max_length = 255)
	body = RichTextField(config_name = "default")
	created_on = models.DateTimeField(auto_now_add=True)
	last_modified = models.DateTimeField(auto_now=True)
	categories = models.ManyToManyField('Category', related_name='posts')

	def __str__(self):
		return self.title

core/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
	name = models.CharField(max_length=31)
	description = models.CharField(max_length = 255)
	color = models.CharField(max_length = 7)
	href = models.CharField(max_length = 31)

	def __str__(self):
		return self.name

webapps/models.py
from django.db import models

# Create your models here.
class WebApp(models.Model):
	title = models.CharField(max_length = 255)
	description = models.CharField(max_length = 255)
	github = models.URLField(max_length = 255)
	ref = models.CharField(max_length = 63)

	def __str__(self):
		return self.title

blog/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.
def blog_index(request):
    posts = Post.objects.all().order_by('-created_on')
    
    context = {
        "posts": posts,
        "title": "Blog"
    }
    
    return render(request, "blog/blog_index.html", context)

def post_detail(request, pk):
    post = Post.objects.get(pk = pk)

    context = {
        "post": post,
        "title": "Blog"
    }


    return render(request, "blog/blog_post.html", context)

core/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
	return render(request, 'core/index.html')

def resume(request):
	context = {
		"title": "Resume"
	}
	return render(request, 'core/resume.html', context)

webapps/views.py
from django.shortcuts import render, redirect
from .models import WebApp
from .utils.lyric_cloud import *

# Create your views here.
def webapps(request):
	WebApps = WebApp.objects.all()
	context = {
		"WebApps" : WebApps
	}
	return render(request, 'webapps/webapps_index.html', context)

def lyric_cloud(request):
	print(request.method)
	if request.method == 'POST':
		login = user_login()
		return login

	else:
		code = request.GET.get("code", '')

		if code:
			tk = get_access_token(code)
			html_cloud = generate_lyric_cloud(tk)

			context = {
				'cloud' : html_cloud
			}
			return render(request, 'webapps/lyric_cloud.html', context)
		else:
			return render(request, 'webapps/lyric_cloud.html')


"""
def lyric_cloud_auth(request):
	spotify = None
	print(request.method)
	if request.method == 'POST':
		user_login()


	return render(request, 'webapps/lyric_cloud.html')	
"""

blog/templates/blog/blog_index.html
{% extends "base.html"%}
{% block content %}


<div class = "container my-5">	
	{% for post in posts %}
	<div class = "row">
		<div class = "col-md-8">
			<a class = "" href = "{% url 'blog:post_detail' post.pk  %}">
				<h2 class = "blog-title title mt-3"> 
				{{post.title}}
				</h2>
			</a>
			<p class = "post-about">
			by Jordan Wells | Posted on {{post.created_on|date:"F d, Y"}} </p>
			<p class = "blog-desc"> {{ post.description}}</p>
		</div>
	
	</div>
	{% endfor %}
	<div style = "padding-bottom: 250px">
	</div>
</div>

{% endblock content %}

blog/templates/blog/blog_post.html
{% extends "base.html"%}
{% block content %}

<div class = "container my-5">
	<div class = "row my-3">
		<a  class = "title blog-back" href = "{% url 'blog:blog_index' %}"> <h2 class = "title blog-back">back to posts</h2> </a>
	</div>
	<div class = "row my-3">
			<h2 class = "post-title title"> {{post.title}}</h2>
	</div>
	<div class = "row">
			<p class = "post-about">
				by Jordan Wells | Posted on {{post.created_on|date:"F d, Y"}} 
			</p>
	</div>
	<div class = "row">
			<div class = "col-md-10">
				<p class = "post-body"> {{post.body | safe }} </p>
			</div>
	</div>
	
</div>

{% endblock content %}

core/templates/core/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<!---Top Picture--->
	<div class = "">
		<div class = "container-fluid top-picture" style = "background-image: url({% static 'clock_knot.jpg' %}); background-size: cover;">
			<div class = "row top-row">
				<div class = "col-lg-12 top-text">
					<h1 class = "top-title"> Jordan Wells </h1>
				</div>
			</div>
		</div>
	</div>

	<!-- About me -->
	<div class = "about-content" >
		<div class="container about-content" >

			<div class = "row justify-content-center">
				<h2 class = "title">Hi!</h2>
			</div>

			<div class="row justify-content-center">
				<div class="col-lg-12">	
					<p class = "description">
						I'm just a curious guy fumbling my way around topics I find interesting. 
					</p>
					<p class = "description mt-4">
						I hope you enjoy this site as much as I did learning how to make it!
					</p>
				</div>
			</div>
		</div>
	</div>

	<!---What do I do? Section--->
	<div class = "what-content" >
		<div class="container" >
			<div class = "row justify-content-center mb-3">
				<h2 id="about" class = "title">What do I do?</h2>
			</div>
			<div class="row justify-content-between my-3">
				<div class="col-lg-6">
						<h3 class = "what-subtitle" style = "color: #7dc9a7;">Chemical Engineering</h3>
						<div>
							<p class = "description what-description">
								Studying chemical engineering has been a wonderful vessel for allowing me to find interesting aspects of math and science that power our modern existence.
							</p>
							<p class = "description what-description">
								Currently, my interests are focused on biotechnology, computational biology, and materials science.
							</p>
						</div>
				</div>

				<div class = "col-lg-5">
					<img class = "what-img" src = "{% static 'dna_icon.svg'%}" alt = "A DNA double-helix icon">
				</div>

			</div>
			<div class="row flex-column-reverse flex-lg-row justify-content-between">

				<div class = "col-lg-5">
					<img class = "what-img" src = "{% static 'code_icon.svg'%}" alt = "A computer screen showing a code text editor">
				</div>

				<div class="col-lg-6">
					<h3 class = "what-subtitle" style = "color: #71c78f;">Programming</h3>
					<div >
						<p class = "description what-description">
							Computer programming has been such a powerful tool in the way I express my creativity, allowing me to create swaying data visualizations, practical applications, and fun side-projects.
						</p>
						<p class = "description what-description">
							Currently, my interests in programming are focused on exploring the wide space of data science.
						</p>
					</div>
				</div>

			</div>	
		</div>
	</div>

	<!---Projects--->
	<div>
		<div class="container-fluid" style = "background-color: #403233;">	
			<div class="row justify-content-center" >
				<h2 class ="title mt-5" id = "projects">Projects</h2>
			</div>
			<div class = "row justify-content-center">
				<p class = "col-lg-12 project-description description mb-5">A few things I've done on the side</p>
			</div>	
		</div>

		<div class = "container-fluid" style = "background-color: #615959;">

			<a class = "project-col" href = "https://github.com/jordantwells42/">
				<div class="row justify-content-center project-card project-card-1">
					<div class = "col-12">
						<h2 class = "title mt-5 justify-content-center project-card-title">
							GITHUB
						</h2>
					</div>
					<div class = "col-8 justify-content-center mb-4">
						<p class = "project-description description">
							Where you can find all the programming projects I'm working on
						</p>
					</div>
					
				</div>
			</a>

		    <a class = "project-col" href = "#top">
				<div class="row justify-content-center project-card project-card-2">
					<div class = "col-12">
						<h2 class = "title mt-5 justify-content-center project-card-title">
							THIS WEBSITE!
						</h2>
					</div>
					<div class = "col-8 justify-content-center mb-4">
						<p class = "project-description description">
							Hand-coded with the Django Python Web-framework, HTML, CSS, and JavaScript
						</p>
					</div>
					
				</div>
			</a>

			<a class = "project-col" href = "blog/">
				<div class="row justify-content-center project-card project-card-3">
					<div class = "col-12">
						<h2 class = "title mt-5 justify-content-center project-card-title">
							MY BLOG
						</h2>
					</div>
					<div class = "col-8 justify-content-center mb-4">
						<p class = "project-description description">
							A place where I talk about the things I am learning
						</p>
					</div>
					
				</div>
			</a>

		</div>
	</div>
		
{% endblock content %}

core/templates/core/resume.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class = "container my-5">
		<!-- Name and Contact -->

		<div class = "row">
			<div class = "col-sm-8">
				<h1 class = "resume-name">Jordan Wells</h1>
				<h2 class = "resume-header"> Chemical Engineer, Data Science Hobbyist</h2>
			</div>
			<div class = "col-sm-4">
				<h2 class = "resume-header" style = "padding-top: 1rem;"> Contact: </h2>
				<p class = "resume-contact">
					(281) 608-1825 <br>
					jordantwells@gmail.com <br>
					<a href = "https://www.jordantwells.com">
						jordantwells.com
					</a>
					<a href = "https://www.linkedin.com/in/jordantwells/">
						linkedin.com/in/jordantwells
					</a>
				</p>
			</div>
		</div>

		<!-- Education -->

		<h2 class = "resume-header">
			Education <hr>
		</h2>
		<div class = "row justify-content-between">
			<div class = "col-md-9">	
				<h3 class = "resume-position">
					Bachelor of Science in Chemical Engineering
				</h3>
				<h4 class = "resume-position-sub"> 
					The University of Texas at Austin
				</h4>
			</div>
			<h3 class = "col-md-3 resume-date">
				08/2019 - 05/2023
			</h3>
		</div>
		<ul class = "resume-info">
			<li>Overall GPA: <strong>4.00</strong>, Major GPA: <strong>4.00</strong></li>

			<li>Relevent Courses: Physical Chemistry, Transport Phenomena, Engineering Statistics</li>
		</ul>
		<br>

		<!-- Experience -->

		<h2 class = "resume-header">
			Experience <hr>
		</h2>

		<!-- Position 1 -->
		<div class = "row justify-content-between">
			<div class = "col-md-9">
				<h3 class = "resume-position">
					Undergraduate Research Assistant
				</h3>
				<h4 class = "resume-position-sub"> 
					Alper Group, UT Austin
				</h4>
			</div>
			<h3 class = "col-md-3 resume-date">
				11/2019 – Present
			</h3>
		</div>
			<ul class = "resume-info">
				<li>
					Direct the evolution of bacterial cells to produce novel enzyme functionality
				</li>
				<li>
					Collaborate in the implementation of cellular biosensors to streamline current methodology
				</li>
				<li>
					Utilize Rosetta Software to predict and design protein structure
				</li>
				<li>
					Visualize and analyze collected data using Python data science libraries
				</li>
			</ul>
		<br>

		<!-- Position 2 -->
		<div class = "row justify-content-between">
			<div class = "col-md-9">
				<h3 class = "resume-position">
					Academic Tutor
				</h3>
				<h4 class = "resume-position-sub"> 
					Austin Learning Center
				</h4>
			</div>
			<h3 class = "col-md-3 resume-date">
				08/2020 – Present
			</h3>
		</div>
			<ul class = "resume-info">
				<li>
					Collaborate with students to get the most out of their STEM education
				</li>
				<li>
					Tailor lesson plans to accommodate student's specific academic strengths and wants
				</li>
				<li>
					Organize records of academic performance to achieve student improvement
				</li>
			</ul>
		<br>

		<!-- Skills -->
		<h2 class = "resume-header">
			Skills and Proficiencies <hr>
		</h2>
		<ul class = "resume-info">
			<li>
				Proficient in Python (Django, Pandas, Matplotlib), HTML, CSS, and Excel
			</li>
			<li>
				Experienced with Java, Javascript, AutoCAD, Biotechnology Tools, Photoshop, and Illustrator
			</li>
		</ul>
		<br>


		<!-- Accomplishments -->
		<h2 class = "resume-header">
			Accomplishments <hr>
		</h2>
		<ul class = "resume-info">
			<li>Freshmen Representative and Service Chair, Texas AIChE</li>
			<li>University Honors</li>
			<li>UIL Science 6A Academic State Champion</li>
			<li>National Merit Finalist and National Hispanic Scholar</li>
			<li>Atascocita High School Salutatorian</li>
			<li>American Chemical Society – Greater Houston Section Scholarship Exam winner</li>
			<li>President, UIL Math and Science League</li>
		</ul>
		<br>
		
	</div>
	<a class = "title" href = "{% static 'jordanwellsresume.pdf' %}" download>
		<p class = "resume-download">Download a PDF version here</p>
	</a>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta name="description" content ="The personal website for Jordan Wells, a UT Chemical Engineering student and programming hobbyist"> 

	<meta property="og:title" content ="Jordan Wells">
	<meta property="og:description" content ="Jordan Wells' Personal Website">
	<meta property="og:type" content ="website">
	<meta property="og:url" content ="https://www.jordantwells.com/">
	<meta property="og:image" content ="{% static Jordan.JPG %}">
	<meta property="og:site_name" content ="Jordan Wells">





	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" 
          href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/styles/default.min.css">
    <link rel="stylesheet" type="text/css" href= "{% static 'css/styles.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kalam|Roboto">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="icon" href="{% static 'favicon.png'%}" type="png" />

	{% if title %}
		<title> Jordan Wells - {{ title }} </title>
	{% else %}
		<title> Jordan Wells </title>
	{% endif %}
</head>
<style>
	.contact-img {
	display: block;
	background-image: url({% static 'icons/envelope.svg'%});
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	height: 100px;
	width: 100px;
	fill:#FFFFFF;
	margin-bottom: 20px;
  	transition: 0.005s;
	}
	
	.contact-img:hover {
  	background-image: url({% static 'icons/envelope-open.svg'%});
	}


</style>
<body style = "background-color: #FFF9FB;">
	<!---Navigation Bar--->
	<nav class="navbar fixed-top navbar-expand-md">
	    <div class="container">
	        <a class="navbar-brand" href="{% url 'core:index' %}"><img class = "nav-img" src = "{% static 'favicon.png'%}" alt = "My Logo"></img> </a>
	         <button class="navbar-dark navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    			<span class="navbar-toggler-icon"></span>
  			</button>
	        <div class="collapse navbar-collapse" id="navbarNav">
	            <ul class="navbar-nav ml-auto" >

	                <li class="nav-item">
	                    <a class="nav-link scroll-link" href= "{% url 'core:index' %}">Home</a>
	                </li>

	                <li class="nav-item">
	                    <a class="nav-link scroll-link" href="{% url 'blog:blog_index' %}">Blog</a>
	                </li>

	                <li class="nav-item">
	                    <a class="nav-link scroll-link" href="{% url 'core:resume' %}">Resume</a>
	                </li>
	                
	            </ul>
	        </div>
	    </div>
	</nav>


	{% block content %}
	{% endblock content %}

	<!---Contact Section--->
	<div>
		<div class="container-fluid" style = "background-color: #403233;">
			<div class="row">
				<div class = "col-12">
	                <h2 class ="title mt-3 mb-2" id = "contact" style = "text-align: center">Contact</h2>
	                <h3 class = "" style = "color: snow; text-align: center"> +1 (281) 608-1825</h3>
	            </div>
		    </div>
			<div class = "row justify-content-center">
				<a href = "mailto:jordantwells@gmail.com" class = "justify-content-center">
				<div class = "contact-img">
				</div>
				</a>
			</div>	
		</div>
	</div>

	<!---Footer Section--->
	<div class = "footer-content">
		<div class = "container-fluid" style = "background-color :#F7A474">
			<div class = "row" style = "height: 75px">
			</div>
		</div>
	</div>


	<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	
</body>
</html>

webapps/templates/webapps/lyric_cloud.html
{% extends "base.html"%}
{% block content %}
{% if not has_auth %}
<form action='' method='Post'>
	 {% csrf_token %}
	<button type='submit'> Spoop</button>
</form>
{% endif %}
{% if cloud %}
{{cloud}}
{% endif %}
<h1>{{spotify}}</h1>
{% endblock content %}

webapps/templates/webapps/webapps_index.html
{% extends "base.html"%}
{% block content %}
<div class = "container ">
	<div class = "row justify-content-center">
		<h3 class = "col-12 title mt-5">
			Welcome to my Web Apps
		</h3>
	</div>
</div>
	<div class = "container my-4">
		{% for WebApp in WebApps %}
		
			<div class = "webapp-card card mb-3">
				<a href = "{{WebApp.ref}}">
				<h1 class = "webapp-title title mb-3">{{WebApp.title}}</h1>
				</a>
				<p class = "description" style = "text-align: left">{{WebApp.description}}</p>
				<a href = "{{WebApp.github}}">GitHub Link</a>
			</div>

		
		{% endfor %}
	</div>
{% endblock content %}